execute @e[tag=UHC,score_RandomTeams=1,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join red @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=2,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join blue @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=3,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join green @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=4,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join yellow @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=5,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join gold @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=6,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join purple @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=7,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join aqua @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=8,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join dark_gray @r[team=NoTeam]
execute @e[tag=UHC,score_RandomTeams=9,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join white @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=10,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join black @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=11,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join dark_blue @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=12,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join dark_green @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=13,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join dark_aqua @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=14,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join dark_red @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=15,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join light_purple @r[team=NoTeam,c=1]
execute @e[tag=UHC,score_RandomTeams=16,score_RandomTeams_min=1] ~ ~ ~ /scoreboard teams join gray @r[team=NoTeam,c=1]

function uhc:jointeams if @a[team=NoTeam]